import { Target } from '../Interfaces/KPIInterface'

export const dummyTargets: Target[] = [
  {
    TargetName: 'Call 50 Leads',
    TargetValue: 50,
    TargetAchieved: true,
    ValueAchieved: 50,
    AchievedOn: new Date('2025-10-15'),
    Priority: 'High',
    PointsGained: 100,
    TotalPoints: 100,
  },
  {
    TargetName: 'Book 10 Student Meetings',
    TargetValue: 10,
    TargetAchieved: false,
    ValueAchieved: 7,
    Priority: 'Medium',
    PointsGained: 35,
    TotalPoints: 50,
  },
  {
    TargetName: 'Close 5 Admissions',
    TargetValue: 5,
    TargetAchieved: true,
    ValueAchieved: 5,
    AchievedOn: new Date('2025-09-30'),
    Priority: 'High',
    PointsGained: 80,
    TotalPoints: 80,
  },
  {
    TargetName: 'Follow Up with 20 Leads',
    TargetValue: 20,
    TargetAchieved: false,
    ValueAchieved: 12,
    Priority: 'Low',
    PointsGained: 24,
    TotalPoints: 40,
  },
  {
    TargetName: 'Send 30 Emails',
    TargetValue: 30,
    TargetAchieved: false,
    ValueAchieved: 25,
    Priority: 'Medium',
    PointsGained: 50,
    TotalPoints: 60,
  },
  {
    TargetName: 'Schedule 3 Webinars',
    TargetValue: 3,
    TargetAchieved: true,
    ValueAchieved: 3,
    AchievedOn: new Date('2025-10-05'),
    Priority: 'High',
    PointsGained: 60,
    TotalPoints: 60,
  },
  {
    TargetName: 'Collect 15 Testimonials',
    TargetValue: 15,
    TargetAchieved: false,
    ValueAchieved: 9,
    Priority: 'Medium',
    PointsGained: 45,
    TotalPoints: 75,
  },
  {
    TargetName: 'Create 5 Marketing Videos',
    TargetValue: 5,
    TargetAchieved: true,
    ValueAchieved: 5,
    AchievedOn: new Date('2025-08-20'),
    Priority: 'Low',
    PointsGained: 40,
    TotalPoints: 40,
  },
  {
    TargetName: 'Generate 100 New Leads',
    TargetValue: 100,
    TargetAchieved: false,
    ValueAchieved: 73,
    Priority: 'High',
    PointsGained: 120,
    TotalPoints: 150,
  },
  {
    TargetName: 'Publish 4 Blog Posts',
    TargetValue: 4,
    TargetAchieved: true,
    ValueAchieved: 4,
    AchievedOn: new Date('2025-09-12'),
    Priority: 'Medium',
    PointsGained: 40,
    TotalPoints: 40,
  },
]
